version: '3.9'
services:
  node:
    image: ma_super_app
    container_name: node-app
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db 
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user1
      DATABASE_PASSWORD: P@ssw0rd
      DATABASE_NAME: test
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user1
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: test